# Generated by Django 5.2.5 on 2025-08-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actages',
            new_name='act',
        ),
    ]
